using GymAppV3.Core.Models;
using GymAppV3.Infrastructure.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GymAppV3.Infrastructure.Data.Mappings;

/// <summary>
/// EF Core configuration for the Booking entity
/// Defines database structure for member class bookings/registrations
/// </summary>
public class BookingMap : IEntityTypeConfiguration<Booking>
{
    public void Configure(EntityTypeBuilder<Booking> builder)
    {
        // Map to "Bookings" table in "dbo" schema
        builder.ToTable("Bookings", "dbo");

        // Define primary key
        builder.HasKey(x => x.Id);

        // ID is generated by application (Guid.NewGuid()), not by database
        builder.Property(x => x.Id)
            .ValueGeneratedNever();

        // Booking status (enum converted to string) - required with max 32 characters (e.g., "Confirmed", "Cancelled", "Pending")
        builder.Property(x => x.Status)
            .IsRequired()
            .HasConversion<string>()
            .HasMaxLength(TextSizePresets.XS32);

        // Timestamp when the booking was made - required
        builder.Property(x => x.BookedAt)
            .IsRequired();

        // Timestamp when the booking was cancelled - optional (null if still active)
        builder.Property(x => x.CancelledAt);

        // Relationship to Member - required, cascade delete prevented to maintain referential integrity
        builder.HasOne(x => x.Member)
            .WithMany()
            .HasForeignKey(x => x.MemberId)
            .OnDelete(DeleteBehavior.Restrict);

        // Relationship to ClassSession - required, cascade delete prevented to maintain referential integrity
        builder.HasOne(x => x.ClassSession)
            .WithMany()
            .HasForeignKey(x => x.ClassSessionId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
