using GymAppV3.Core.Models;
using GymAppV3.Infrastructure.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GymAppV3.Infrastructure.Data.Mappings;

/// <summary>
/// EF Core configuration for the ClassSession entity
/// Defines database structure for scheduled gym classes
/// </summary>
public class ClassSessionMap : IEntityTypeConfiguration<ClassSession>
{
    public void Configure(EntityTypeBuilder<ClassSession> builder)
    {
        // Configure table name, with a defense-in-depth check constraint preventing an
        // oversold session. Business rules should stop this long before the database does.
        builder.ToTable("ClassSessions", "dbo", t =>
            t.HasCheckConstraint("CK_ClassSession_AvailableSeats",
                "[AvailableSeats] >= 0 AND [AvailableSeats] <= [Capacity]"));

        // Define primary key
        builder.HasKey(x => x.Id);

        // ID is generated by application (Guid.NewGuid()), not by database
        builder.Property(x => x.Id)
            .ValueGeneratedNever();

        // Class title/name - required with max 512 characters (e.g., "Morning Yoga", "CrossFit 101")
        builder.Property(x => x.Title)
            .IsRequired()
            .HasMaxLength(TextSizePresets.M512);

        // Date and time when the class session begins - required
        builder.Property(x => x.StartsAt)
            .IsRequired();

        // Date and time when the class session ends
        builder.Property(x => x.EndsAt)
            .IsRequired();

        // Duration of the class in minutes - required and must be > 0
        builder.Property(x => x.DurationInMinutes)
            .IsRequired();
        // Note: Validation occurs in ClassSession.IsValid() method

        // Maximum capacity - required and must be > 0
        builder.Property(x => x.Capacity)
            .IsRequired();
        // Note: Validation occurs in ClassSession.IsValid() method

        // Available seats counter
        builder.Property(x => x.AvailableSeats)
            .IsRequired();

        // RowVersion is configured centrally in ApplicationDbContext.OnModelCreating,
        // because its setup differs by provider (SQL Server rowversion vs SQLite fallback).
        builder.Property(x => x.RowVersion)
            .IsRequired();

        // Relationship to Trainer - required, cascade delete prevented to maintain referential integrity
        builder.HasOne(x => x.Trainer)
            .WithMany()
            .HasForeignKey(x => x.TrainerId)
            .OnDelete(DeleteBehavior.Restrict);

        // Relationship to ClassRoom - required, cascade delete prevented to maintain referential integrity
        builder.HasOne(x => x.ClassRoom)
            .WithMany()
            .HasForeignKey(x => x.ClassRoomId)
            .OnDelete(DeleteBehavior.Restrict);

        // A session belongs to one category; a category has many sessions.
        builder.HasOne(x => x.ClassCategory)
            .WithMany()
            .HasForeignKey(x => x.ClassCategoryId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
