using GymAppV3.Core.Models;
using GymAppV3.Infrastructure.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GymAppV3.Infrastructure.Data.Mappings;

/// <summary>
/// EF Core configuration for the ClassRoom entity
/// Defines database structure for gym class spaces
/// </summary>
public class ClassRoomMap : IEntityTypeConfiguration<ClassRoom>
{
    public void Configure(EntityTypeBuilder<ClassRoom> builder)
    {
        // Configure table name, with a check constraint guarding against non-positive capacity.
        builder.ToTable("ClassRooms", "dbo", t =>
            t.HasCheckConstraint("CK_ClassRoom_Capacity", "[Capacity] > 0"));

        // Define primary key
        builder.HasKey(x => x.Id);

        // ID is generated by application (Guid.NewGuid()), not by database
        builder.Property(x => x.Id)
            .ValueGeneratedNever();

        // Classroom name/identifier is required with max 512 characters (e.g., "Room A", "Yoga Studio")
        builder.Property(x => x.ClassRoomName)
            .IsRequired()
            .HasMaxLength(TextSizePresets.M512);

        // Physical seat count. Must be positive — a room with zero capacity cannot host
        // a session, and a negative value is meaningless.
        builder.Property(x => x.Capacity)
            .IsRequired();

        // A room name is unique within its building, among active rooms only.
        builder.HasIndex(x => new { x.GymBuildingId, x.ClassRoomName })
            .IsUnique()
            .HasFilter("[IsDeleted] = 0");
    }

    
}
