using GymAppV3.Core.Models;
using GymAppV3.Infrastructure.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;


namespace GymAppV3.Infrastructure.Data.Mappings;

/// <summary>
/// EF Core configuration for the GymBuilding entity
/// Defines table structure, constraints, and relationships for gym facilities
/// </summary>
public class GymBuildingMap : IEntityTypeConfiguration<GymBuilding>
{
    public void Configure(EntityTypeBuilder<GymBuilding> builder)
    {
        // Map to "GymBuildings" table in "dbo" schema
        builder.ToTable("GymBuildings", "dbo");

        // Define primary key
        builder.HasKey(x => x.Id);

        // ID is generated by application (Guid.NewGuid()), not by database
        builder.Property(x => x.Id)
            .ValueGeneratedNever();

        // Gym name is required with max 32 characters
        builder.Property(x => x.Name)
            .IsRequired()
            .HasMaxLength(TextSizePresets.XS32);

        // Optional description with max 4000 characters
        builder.Property(x => x.Description)
            .HasMaxLength(TextSizePresets.L1024);

        // Address as owned entity — columns live inside the Members table.
        builder.OwnsOne(x => x.Address, address =>
        {
            address.Property(a => a.Street)
                .IsRequired()
                .HasMaxLength(TextSizePresets.M256)
                .HasColumnName("Street");

            address.Property(a => a.City)
                .IsRequired()
                .HasMaxLength(TextSizePresets.S64)
                .HasColumnName("City");

            address.Property(a => a.State)
                .IsRequired()
                .HasMaxLength(TextSizePresets.S64)
                .HasColumnName("State");

            address.Property(a => a.ZipCode)
                .IsRequired()
                .HasMaxLength(TextSizePresets.XS32)
                .HasColumnName("ZipCode");

            address.Property(a => a.Country)
                .IsRequired()
                .HasMaxLength(TextSizePresets.S64)
                .HasColumnName("Country");
        });

        // Optional phone number with max 32 characters
        builder.Property(x => x.Phone)
            .HasMaxLength(TextSizePresets.XS32);

        // Optional email with max 64 characters
        builder.Property(x => x.Email)
            .HasMaxLength(TextSizePresets.S64);
    }
}
