using GymAppV3.Core.Models;
using GymAppV3.Infrastructure.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GymAppV3.Infrastructure.Data.Mappings;

/// <summary>
/// EF Core configuration for the MembershipPackage entity
/// Defines database structure for membership subscription tiers
/// </summary>
public class MembershipPackageMap : IEntityTypeConfiguration<MembershipPackage>
{
    public void Configure(EntityTypeBuilder<MembershipPackage> builder)
    {
        // Map to "MembershipPackages" table in "dbo" schema
        builder.ToTable("MembershipPackages", "dbo");

        // Define primary key
        builder.HasKey(x => x.Id);

        // ID is generated by application (Guid.NewGuid()), not by database
        builder.Property(x => x.Id)
            .ValueGeneratedNever();

        // Package name is required with max 512 characters (e.g., "Basic", "Premium", "VIP")
        builder.Property(x => x.Name)
            .IsRequired()
            .HasMaxLength(TextSizePresets.M512);

        // Price is required, stored as decimal(18,2) for financial precision
        builder.Property(x => x.Price)
            .IsRequired()
            .HasColumnType("decimal(18,2)");

        // Duration in days is required - how long the membership remains valid
        builder.Property(x => x.DurationInDays)
            .IsRequired();

        // Number of class sessions included in the package is required
        builder.Property(x => x.SessionsIncluded)
            .IsRequired();
    }
}
