using GymAppV3.Core.Models;
using GymAppV3.Infrastructure.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GymAppV3.Infrastructure.Data.Mappings;

/// <summary>
/// EF Core configuration for the Membership entity
/// Defines database structure for member subscriptions
/// </summary>
public class MembershipMap : IEntityTypeConfiguration<Membership>
{
    public void Configure(EntityTypeBuilder<Membership> builder)
    {
        // Configure table name, with a defense-in-depth check constraint: the database
        // rejects a negative session balance even if application logic fails to catch it.
        builder.ToTable("Memberships", "dbo", t =>
            t.HasCheckConstraint("CK_Membership_RemainingSessions",
                "[RemainingSessions] >= 0"));

        // Define primary key
        builder.HasKey(x => x.Id);

        // ID is generated by application (Guid.NewGuid()), not by database
        builder.Property(x => x.Id)
            .ValueGeneratedNever();

        // Price paid for membership - required, stored as decimal(18,2) for financial accuracy
        builder.Property(x => x.PricePaid)
            .IsRequired()
            .HasColumnType("decimal(18,2)");

        // Membership start date - required
        builder.Property(x => x.StartDate)
            .IsRequired();

        // Membership expiration date - required
        builder.Property(x => x.EndDate)
            .IsRequired();

        // Counter for remaining class sessions - required
        builder.Property(x => x.RemainingSessions)
            .IsRequired();

        // Membership status (enum converted to string) - required with max 32 characters (e.g., "Active", "Expired", "Cancelled")
        builder.Property(x => x.Status)
            .IsRequired()
            .HasConversion<string>()
            .HasMaxLength(TextSizePresets.XS32);

        // Relationship to Member - required, cascade delete prevented
        builder.HasOne(x => x.Member)
            .WithMany()
            .HasForeignKey(x => x.MemberId)
            .OnDelete(DeleteBehavior.Restrict);

        // Relationship to MembershipPackage - required, cascade delete prevented
        builder.HasOne(x => x.MembershipPackage)
            .WithMany()
            .HasForeignKey(x => x.MembershipPackageId)
            .OnDelete(DeleteBehavior.Restrict);

        // RowVersion is configured centrally in ApplicationDbContext.OnModelCreating,
        // because its setup differs by provider (SQL Server rowversion vs SQLite fallback).
        builder.Property(x => x.RowVersion)
            .IsRequired();
    }
}
