using GymAppV3.Core.Models;
using GymAppV3.Infrastructure.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GymAppV3.Infrastructure.Data.Mappings;

/// <summary>
/// EF Core configuration for the Member entity
/// Defines database structure for gym members and their profiles
/// </summary>
public class MemberMap : IEntityTypeConfiguration<Member>
{
    public void Configure(EntityTypeBuilder<Member> builder)
    {
        // Map to "Members" table in "dbo" schema
        builder.ToTable("Members", "dbo");

        // Define primary key
        builder.HasKey(x => x.Id);

        // ID is generated by application (Guid.NewGuid()), not by database
        builder.Property(x => x.Id)
            .ValueGeneratedNever();

        // User ID reference (links to authentication system) - required with max 64 characters
        builder.Property(x => x.UserId)
            .IsRequired()
            .HasMaxLength(TextSizePresets.S64);

        // Member's first name - required with max 512 characters
        builder.Property(x => x.Firstname)
            .IsRequired()
            .HasMaxLength(TextSizePresets.M512);

        // Member's last name - required with max 512 characters
        builder.Property(x => x.Lastname)
            .IsRequired()
            .HasMaxLength(TextSizePresets.M512);

        // Email address - required with max 256 characters
        builder.Property(x => x.Email)
            .IsRequired()
            .HasMaxLength(TextSizePresets.M256);

        // Email is unique among ACTIVE members only. A soft-deleted member's email can be
        // reused by a new registration — without the filter, the deleted row would block it.
        builder.HasIndex(x => x.Email)
            .IsUnique()
            .HasFilter("[IsDeleted] = 0");

        // Phone number is optional with max 64 characters
        builder.Property(x => x.Phone)
            .HasMaxLength(TextSizePresets.S64);

        // Address as owned entity — columns live inside the Members table.
        builder.OwnsOne(x => x.Address, address =>
        {
            address.Property(a => a.Street)
                .IsRequired()
                .HasMaxLength(TextSizePresets.M256)
                .HasColumnName("Street");

            address.Property(a => a.City)
                .IsRequired()
                .HasMaxLength(TextSizePresets.S64)
                .HasColumnName("City");

            address.Property(a => a.State)
                .IsRequired()
                .HasMaxLength(TextSizePresets.S64)
                .HasColumnName("State");

            address.Property(a => a.ZipCode)
                .IsRequired()
                .HasMaxLength(TextSizePresets.XS32)
                .HasColumnName("ZipCode");

            address.Property(a => a.Country)
                .IsRequired()
                .HasMaxLength(TextSizePresets.S64)
                .HasColumnName("Country");
        });

        // Member's date of birth - required
        builder.Property(x => x.BirthDate)
            .IsRequired();

        // Explicit health declaration — the member must answer, cannot skip.
        builder.Property(x => x.HasMedicalConditions)
            .IsRequired();

        // Optional health details. Conditionally required in the validation layer
        // when HasMedicalConditions is true. Sensitive data (GDPR Art. 9).
        builder.Property(x => x.MedicalNotes)
            .HasMaxLength(TextSizePresets.L1024);

    }
}
