using GymAppV3.Core.Models;
using GymAppV3.Infrastructure.Data.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GymAppV3.Infrastructure.Data.Mappings;

/// <summary>
/// EF Core configuration for the Trainer entity
/// Defines database structure for gym instructors and their profiles
/// </summary>
public class TrainerMap : IEntityTypeConfiguration<Trainer>
{
    public void Configure(EntityTypeBuilder<Trainer> builder)
    {
        // Map to "Trainers" table in "dbo" schema
        builder.ToTable("Trainers", "dbo");

        // Define primary key
        builder.HasKey(x => x.Id);

        // ID is generated by application (Guid.NewGuid()), not by database
        builder.Property(x => x.Id)
            .ValueGeneratedNever();

        // User ID reference (links to authentication system) - required with max 64 characters
        builder.Property(x => x.UserId)
            .IsRequired()
            .HasMaxLength(TextSizePresets.S64);

        // Trainer's first name - required with max 512 characters
        builder.Property(x => x.Firstname)
            .IsRequired()
            .HasMaxLength(TextSizePresets.M512);

        // Trainer's last name - required with max 512 characters
        builder.Property(x => x.Lastname)
            .IsRequired()
            .HasMaxLength(TextSizePresets.M512);

        // Email address - required with max 256 characters
        builder.Property(x => x.Email)
            .IsRequired()
            .HasMaxLength(TextSizePresets.M256);

        // Email is unique among active trainers only.
        builder.HasIndex(x => x.Email)
            .IsUnique()
            .HasFilter("[IsDeleted] = 0");

        // Phone number is optional with max 64 characters
        builder.Property(x => x.Phone)
            .HasMaxLength(TextSizePresets.S64);

        // Professional biography/background with max 4000 characters
        builder.Property(x => x.Bio)
            .HasMaxLength(TextSizePresets.XL4000);
    }
}